apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-web-app
  description: Demo Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'carto.run/workload-name=tap-web-app'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
