#@ load("@ytt:data", "data")

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: #@ data.values.artifactId
    test: #@ data.values.enableTesting
    scan: #@ data.values.enableScanning
spec:
  source:
    git:
      url: #@ data.values.gitUrl
      ref:
        branch: #@ data.values.gitBranch
