#@ load("@ytt:data", "data")

#@ def labels():
apps.tanzu.vmware.com/workload-type: web
#@ if/end data.values.enableTesting == False:
test: "false"
#@ if/end data.values.enableScanning == False:
scan: "false"
#@ end

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels: #@ labels()
spec:
  source:
    git:
      url: #@ data.values.gitUrl
      ref:
        branch: #@ data.values.gitBranch
